# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        channels: conda-forge, defaults
        auto-activate-base: true
    - run: conda install -n base conda-build conda-forge-pinning
    - run: conda upgrade -n base conda-build conda-forge-pinning

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: conda build .conda\recipe\ -m %CONDA_PREFIX%\conda_build_config.yaml
